name: Compile LaTeX

on:
  pull_request:
    branches:
      - main

jobs:
  compile_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: root.tex
